Add trace installer in "process-classes" and "process-test-classes" phases
eclipse/xtext-maven pull request #141
Opened 2021-03-18 11:23 UTC by imhotep82

2021-03-18 11:48 UTC, imhotep82 commented
The code is mainly copied from xtext-xtend and slightly adapted to OutputConfiguration. Still a WIP, but perhaps someone has the time to review this. I added a test assertion in the "aggregate" integration test that asserts if a trace file exists. I don't check whether trace information is really inserted into the bytecode or not. I suppose frameworks like Mockito shall not be used here?

2021-03-18 12:46 UTC, cdietrich commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextMojo.java
> +package org.eclipse.xtext.maven;
please add file header

2021-03-18 12:46 UTC, cdietrich commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextMojo.java
> +public abstract class AbstractXtextMojo extends AbstractMojo {
please add `@since`

2021-03-18 12:46 UTC, cdietrich commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/ClassFileDebugSourceExtractor.java
> +class ClassFileDebugSourceExtractor {
please add `@since`

2021-03-18 12:46 UTC, cdietrich commented on org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
> +		verifier.assertFilePresent(verifier.getBasedir() + "/purexbase/src-gen/.IntegrationTestXbase.java._trace");
wonder if we can test if there is information in the class file

2021-03-18 12:55 UTC, imhotep82 commented on org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
> +		verifier.assertFilePresent(verifier.getBasedir() + "/purexbase/src-gen/.IntegrationTestXbase.java._trace");
I'll give it a shot

2021-03-18 13:37 UTC, imhotep82 commented on org.eclipse.xtext.maven.plugin/src/test/java/org/eclipse/xtext/maven/plugin/XtextGeneratorIT.java
> +		verifier.assertFilePresent(verifier.getBasedir() + "/purexbase/src-gen/.IntegrationTestXbase.java._trace");
I'll add a test that asserts that the "patched" source file name is set to "xbase"

2021-03-18 15:28 UTC, imhotep82 commented
Closes #139

2021-03-18 16:07 UTC, cdietrich commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +	private static final String PATH_SEPARATOR = "/";
am not sure about the naming. @szarnekow what do you think.

2021-03-19 07:57 UTC, imhotep82 commented
I noticed a shortcoming of the previous code: The traced files must be filtered by the DSL's file extensions. I filter files to be traced by the file extensions associated with the language setup.

2021-03-19 08:53 UTC, szarnekow requested changes

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextGeneratorMojo.java
> +	 * Subclasses may override
It's an abstract method. Subclasses *must* in fact override. I'd remove the first line of the JavaDoc.

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/AbstractXtextGeneratorMojo.java
> +
Trailing whitespace.

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +	private static final String PATH_SEPARATOR = "/";
As far as I can tell we don't need that PathSeparator. The File API can do all the path work for use, e.g by using `new File(parent, name)`

If we figure that working is String is preferable, I'd rename it to something more specific, e.g. PATH_SEPARATOR_IN_DEBUG_INFO or similar and check it's usages below. Some of these should probably use the separator from java.io.File

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +	protected void collectJavaSourceFile2traceFile(String root, String subdir,
I'd really prefer working with File for root, subdir and the map key.

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +		try (InputStream in = new FileInputStream(traceFile)) {
Nit: We should probably use a BufferedInputStream here

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +		String sourceFileName = traceRegion.getAssociatedSrcRelativePath().getURI().lastSegment();
You can ask the URI for the fileExtension.

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +			Injector injector = Guice.createInjector(new MavenStandaloneBuilderModule());
Languages may customize the trace file names and paths. Here we use a single shared module to inject the members into this class here. That'll do no good.

2021-03-19 08:53 UTC, szarnekow commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +					Injector languageInjector = languageSetup.createInjectorAndDoEMFRegistration();
These injectors must be used to obtain the trace stuff per language.

2021-03-19 08:55 UTC, szarnekow commented
@imhotep82 I think we are on a good way here. Can you please double check the usages of the injectors and the plenty places where String manipulation is done for something that should be offered by java.io.File instead?

2021-03-19 08:58 UTC, imhotep82 commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +			Injector injector = Guice.createInjector(new MavenStandaloneBuilderModule());
you're right, I didn't consider this

2021-03-19 10:36 UTC, imhotep82 commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +					Injector languageInjector = languageSetup.createInjectorAndDoEMFRegistration();
I guess you mean the TraceFileNameProvider?

2021-03-19 10:42 UTC, imhotep82 commented
> @imhotep82 I think we are on a good way here. Can you please double check the usages of the injectors and the plenty places where String manipulation is done for something that should be offered by java.io.File instead?

I refactored the code to use java.nio Files.walk to traverse the directories containing trace files. All of the code now uses java.io.File and the appropriate ctors.
I use the language injector for the trace file names and the file extension(s).

2021-03-19 11:13 UTC, imhotep82 commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +	private static final String PATH_SEPARATOR = "/";
Already removed

2021-03-19 13:38 UTC, imhotep82 commented
@szarnekow I have a question: Can we safely assume that for each class file there is always just one trace file? If so, the code could be condensed a lot.

2021-03-20 10:40 UTC, imhotep82 commented on org.eclipse.xtext.maven.plugin/src/main/java/org/eclipse/xtext/maven/trace/AbstractGenerateTracesMojo.java
> +	private static final String PATH_SEPARATOR = "/";
fyi I changed the names to be more in line with the xtend ones. (-> InstallDebugInfoMojo etc.)

2021-03-24 10:31 UTC, imhotep82 commented
@cdietrich  @szarnekow  I also have a suggestion: Would it be OK if the xtext-maven-plugin added the configured output folders to the (test)compileSourceRoots so the maven-compiler finds the class files? This would be a nice addition imo, because then I wouldn't need to specify the output directories twice, for example in `build-helper-maven-plugin` and `xtext-maven-plugin`.

2021-03-24 10:38 UTC, szarnekow commented
@imhotep82  If I understood your proposal correctly, that would be a nice option that could even be enabled by default.
Users must have a way to opt out from that for whatever reason.

2021-03-24 10:44 UTC, imhotep82 commented
> @imhotep82 If I understood your proposal correctly, that would be a nice option that could even be enabled by default.
> Users must have a way to opt out from that for whatever reason.

I agree, I'll add this as a top-level option of the plugin. Regarding my other question, is there a test-language with which I could test the correct directory structure of generated class files?

2021-03-24 15:03 UTC, imhotep82 commented
There were a few problems with integration tests, hopefully all sorted out now.

2021-04-02 15:07 UTC, imhotep82 commented
> @imhotep82 I think we are on a good way here. Can you please double check the usages of the injectors and the plenty places where String manipulation is done for something that should be offered by java.io.File instead?
Can you review again?

2021-04-08 18:18 UTC, szarnekow approved these changes
Nice work. What I see makes all sense to me. I think we can move this forward.

2021-04-09 04:36 UTC, merged

2021-04-09 04:37 UTC, cdietrich commented
many thanks @imhotep82